'''
Config file for debugging
'''

META:
  NAME : test_NTU_3D_ttspcc2_833_2        #folder name to store trained model and results

MODEL:
  MODEL_TYPE : ttspcc2   #type of model to train, temporal, temporal_2, temporal_3, temporal_4, spatial-temporal or parts
  EMBED_DIM : 32           #embedding dimension used by the model
  SEGMENT_LEN : 24          #length of sliding window (no.of frames)
  DEBUG : TRUE              #load subset of trajectories in debug mode
  DATASET : NTU_3D          #dataset used HR-Crime/UTK/NTU_2D/NTU_3D

DECOMPOSED:
  ENABLE: FALSE                #whether to use globally and locally decomposed trajectories
  TYPE: GR                    #possible values: GR (Global repeated), GS (Global single)

TUBELET:                    #whether to use tubelet embeddings or not
  ENABLE: TRUE            
  KERNEL: 8,3,3           #Kernel+Stride for tubelet embeddings
  STRIDE: 8,3,3
  PAD_MODE: constant      #Could be constant, replicate, reflect

TRAINING:
  EPOCHS : 2              #maximum number of epochs during training
  BATCH_SIZE : 100         #batch size for training
  PATIENCE : 3             #patience before early stopping is enabled
  LR : 0.001                #starting learning rate for adaptive learning
  LR_PATIENCE : 3           #patience before learning rate is decreased
  KFOLD: 2                  #number of folds used for cross-validation
  WEIGHT_DECAY: 0           #weight decay value